export default {
  "AR": "Argentina",
  "BZ": "Belice",
  "BO": "Bolivia",
  "BR": "Brasil",
  "CL": "Chile",
  "CO": "Colombia",
  "CR": "Costa Rica",
  "CU": "Cuba",
  "DO": "República Dominicana",
  "EC": "Ecuador",
  "SV": "El Salvador",
  "GQ": "Guinea Ecuatorial",
  "FK": "Islas Malvinas",
  "GT": "Guatemala",
  "HN": "Honduras",
  "MX": "México",
  "NI": "Nicaragua",
  "PA": "Panamá",
  "PY": "Paraguay",
  "PE": "Perú",
  "PR": "Puerto Rico",
  "ES": "España",
  "US": "Estados Unidos de América",
  "UY": "Uruguay",
  "VE": "Venezuela"
}