export default [
  {title: "Argentina", value: "AR"},
  {title: "Belize", value: "BZ"},
  {title: "Bolivia", value: "BO"},
  {title: "Brazil", value: "BR"},
  {title: "Chile", value: "CL"},
  {title: "Colombia", value: "CO"},
  {title: "Costa Rica", value: "CR"},
  {title: "Cuba", value: "CU"},
  {title: "Dominican Republic", value: "DO"},
  {title: "Ecuador", value: "EC"},
  {title: "El Salvador", value: "SV"},
  {title: "Equatorial Guinea", value: "GQ"},
  {title: "Falkland Islands (Malvinas)", value: "FK"},
  {title: "Guatemala", value: "GT"},
  {title: "Honduras", value: "HN"},
  {title: "Mexico", value: "MX"},
  {title: "Nicaragua", value: "NI"},
  {title: "Panama", value: "PA"},
  {title: "Paraguay", value: "PY"},
  {title: "Peru", value: "PE"},
  {title: "Puerto Rico", value: "PR"},
  {title: "Spain", value: "ES"},
  {title: "United States", value: "US"},
  {title: "Uruguay", value: "UY"},
  {title: "Venezuela", value: "VE"}
]